_BASE_: "../../../../configs/Base-RCNN-DilatedC5.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE:
    FREEZE_AT: 0
  SEM_SEG_HEAD:
    NAME: "DeepLabV3Head"
    IN_FEATURES: ["res5"]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    CONVS_DIM: 256
    COMMON_STRIDE: 16
    NUM_CLASSES: 2
    LOSS_TYPE: "cross_entropy"
DATASETS:
  TRAIN: ("coco_person_sem_seg_train",)
  TEST: ("coco_person_sem_seg_val",)
SOLVER:
  BASE_LR: 0.01
  MAX_ITER: 200000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 3
INPUT:
  MIN_SIZE_TRAIN: (1024, 1280)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (1024, 512)
    SINGLE_CATEGORY_MAX_AREA: 0.8
DATALOADER:
  NUM_WORKERS: 10
TEST:
  AUG:
    ENABLED: False
    FLIP: false
    MIN_SIZES:
      - 1024
    MAX_SIZE: 1024
